Repository AnonymusRaccoon/Bomberman, pull requests merged in 2021-05, with the labels that each got.

#55 Animations containers
  assets/guy.iqm
  assets/guytex.png
  lib/Ray/CMakeLists.txt
  lib/Ray/sources/Camera/Camera2D.cpp
  lib/Ray/sources/Camera/Camera2D.hpp
  lib/Ray/sources/Camera/Camera3D.cpp
  lib/Ray/sources/Camera/Camera3D.hpp
  lib/Ray/sources/Drawables/2D/Triangle.cpp
  lib/Ray/sources/Drawables/2D/Triangle.hpp
  lib/Ray/sources/Drawables/ADrawable3D.hpp
  lib/Ray/sources/Exceptions/RayError.cpp
  lib/Ray/sources/Exceptions/RayError.hpp
  lib/Ray/sources/Model.cpp
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  lib/Ray/sources/Model/ModelAnimation.cpp
  lib/Ray/sources/Model/ModelAnimation.hpp
  lib/Ray/sources/Model/ModelAnimations.cpp
  lib/Ray/sources/Model/ModelAnimations.hpp
  lib/Ray/sources/Window.cpp
  lib/Ray/sources/Window.hpp
  sources/Util/vector.cpp
  sources/main.cpp
Labels: renderer

#56 Issues & Prs Templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  .github/workflows/codingstyle.yml
  eCPPLINT.cfg
  lib/wal/eCPPLINT.cfg
  lib/wal/sources/Component/Component.cpp
  lib/wal/sources/Component/Component.hpp
  lib/wal/sources/Component/Movable/MovableComponent.cpp
  lib/wal/sources/Component/Movable/MovableComponent.hpp
  lib/wal/sources/Component/Position/PositionComponent.cpp
  lib/wal/sources/Component/Position/PositionComponent.hpp
  lib/wal/sources/Entity/Entity.cpp
  lib/wal/sources/Entity/Entity.hpp
  lib/wal/sources/Exception/WalError.cpp
  lib/wal/sources/Exception/WalError.hpp
  lib/wal/sources/Models/Callback.hpp
  lib/wal/sources/Models/Vector3.hpp
  lib/wal/sources/Scene/Scene.cpp
  lib/wal/sources/Scene/Scene.hpp
  lib/wal/sources/System/Movable/MovableSystem.cpp
  lib/wal/sources/System/Movable/MovableSystem.hpp
  lib/wal/sources/System/System.cpp
  lib/wal/sources/System/System.hpp
  lib/wal/sources/Wal.cpp
  lib/wal/sources/Wal.hpp
  lib/wal/tests/CallbackTest.cpp
Labels: High priority

#63 State management, file system cleanup
  .github/workflows/test.yml
  CMakeLists.txt
  lib/wal/CMakeLists.txt
  lib/wal/sources/Models/Callback.hpp
  lib/wal/sources/Scene/SceneManager.hpp
  lib/wal/sources/Wal.cpp
  lib/wal/sources/Wal.hpp
  sources/Component/Movable/MovableComponent.cpp
  sources/Component/Movable/MovableComponent.hpp
  sources/Component/Position/PositionComponent.cpp
  sources/Component/Position/PositionComponent.hpp
  sources/Models/GameState.hpp
  sources/Models/Vector3.hpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/System/Movable/MovableSystem.cpp
  sources/System/Movable/MovableSystem.hpp
  sources/main.cpp
  tests/CallbackTest.cpp
  tests/EngineTests.cpp
  tests/EntityTests.cpp
  tests/MainTest.cpp
Labels: ECS
