Repository AnonymusRaccoon/Bomberman, pull requests merged in 2021-06, with the labels that each got.

#80 Movements
  CMakeLists.txt
  lib/Ray/sources/Controllers/Keyboard.hpp
  lib/Ray/sources/Window.cpp
  lib/Ray/sources/Window.hpp
  sources/Component/Controllable/ControllableComponent.cpp
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Component/Gamepad/GamepadComponent.cpp
  sources/Component/Gamepad/GamepadComponent.hpp
  sources/Component/GridCentered/GridCenteredComponent.cpp
  sources/Component/GridCentered/GridCenteredComponent.hpp
  sources/Component/Health/HealthComponent.cpp
  sources/Component/Health/HealthComponent.hpp
  sources/Component/Keyboard/KeyboardComponent.cpp
  sources/Component/Keyboard/KeyboardComponent.hpp
  sources/Component/Renderer/CameraComponent.cpp
  sources/Component/Renderer/CameraComponent.hpp
  sources/Models/Vector2.hpp
  sources/Models/Vector3.hpp
  sources/Runner/Runner.cpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/Controllable/ControllableSystem.hpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/Gamepad/GamepadSystem.hpp
  sources/System/GridCentered/GridCenteredSystem.cpp
  sources/System/GridCentered/GridCenteredSystem.hpp
  sources/System/Health/HealthSystem.cpp
  sources/System/Health/HealthSystem.hpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/Keyboard/KeyboardSystem.hpp
  sources/System/Movable/MovableSystem.cpp
  sources/System/Renderer/RenderScreenSystem.cpp
  tests/MoveTests.cpp
Labels: Game, component, enhancement

#86 model now use shared ptr + cache system to spare memory
  lib/Ray/sources/Drawables/2D/Circle.cpp
  lib/Ray/sources/Drawables/2D/Line.cpp
  lib/Ray/sources/Drawables/2D/Point.cpp
  lib/Ray/sources/Drawables/2D/Rectangle.cpp
  lib/Ray/sources/Drawables/2D/Rectangle.hpp
  lib/Ray/sources/Drawables/2D/Text.cpp
  lib/Ray/sources/Drawables/2D/Triangle.cpp
  lib/Ray/sources/Drawables/ADrawable2D.cpp
  lib/Ray/sources/Drawables/ADrawable2D.hpp
  lib/Ray/sources/Drawables/Image.cpp
  lib/Ray/sources/Drawables/Image.hpp
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  lib/Ray/sources/Window.cpp
  lib/Ray/sources/Window.hpp
Labels: Encapsulation, renderer

#95 Generic Cache system for ressources
  lib/Ray/CMakeLists.txt
  lib/Ray/sources/Drawables/Image.cpp
  lib/Ray/sources/Drawables/Image.hpp
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  lib/Ray/sources/Font.cpp
  lib/Ray/sources/Font.hpp
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  lib/Ray/sources/Model/ModelAnimations.cpp
  lib/Ray/sources/Model/ModelAnimations.hpp
  lib/Ray/sources/Utils/Cache.hpp
Labels: Encapsulation

#81 Collision Component / System
  CMakeLists.txt
  sources/Component/Collision/CollisionComponent.cpp
  sources/Component/Collision/CollisionComponent.hpp
  sources/Component/Movable/MovableComponent.cpp
  sources/Component/Movable/MovableComponent.hpp
  sources/Models/Vector3.hpp
  sources/Runner/Runner.cpp
  sources/System/Collision/CollisionSystem.cpp
  sources/System/Collision/CollisionSystem.hpp
  tests/CollisionTest.cpp
Labels: component

#100 Animations Component the number :100:
  CMakeLists.txt
  lib/Ray/sources/Model/ModelAnimations.cpp
  lib/Ray/sources/Model/ModelAnimations.hpp
  lib/Ray/sources/Utils/Cache.hpp
  sources/Component/Animation/AnimationsComponent.cpp
  sources/Component/Animation/AnimationsComponent.hpp
  sources/Runner/Runner.cpp
  sources/System/Animation/AnimationsSystem.cpp
  sources/System/Animation/AnimationsSystem.hpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/Controllable/ControllableSystem.hpp
Labels: Game

#99 add basic depths with stairs and bumper to access it
  assets/map/breakable_wall.mtl
  assets/map/breakable_wall.obj
  assets/map/breakable_wall.png
  assets/map/bumper.mtl
  assets/map/bumper.obj
  assets/map/bumper.png
  assets/map/floor.mtl
  assets/map/floor.obj
  assets/map/floor.png
  assets/map/hole.mtl
  assets/map/hole.obj
  assets/map/hole.png
  assets/map/stairs.mtl
  assets/map/stairs.obj
  assets/map/stairs.png
  assets/map/test.mtl
  assets/map/test.obj
  assets/map/test.png
  assets/map/unbreakable_wall.mtl
  assets/map/unbreakable_wall.obj
  assets/map/unbreakable_wall.png
  assets/map/upper_floor.mtl
  assets/map/upper_floor.obj
  assets/map/upper_floor.png
  assets/wall/breakable_wall.png
  assets/wall/hole.png
  sources/Map/Map.cpp
  sources/Map/Map.hpp
Labels: Game

#114 Second floor hole assets #113
  assets/map/upper_floor_hole.mtl
  assets/map/upper_floor_hole.obj
  assets/map/upper_floor_hole.png
  build_web.sh
  sources/Map/Map.cpp
  sources/Map/Map.hpp
Labels: Game

#116 Views of entities and components
  CMakeLists.txt
  lib/wal/CMakeLists.txt
  lib/wal/sources/Entity/Entity.cpp
  lib/wal/sources/Entity/Entity.hpp
  lib/wal/sources/Models/Callback.hpp
  lib/wal/sources/Scene/Scene.cpp
  lib/wal/sources/Scene/Scene.hpp
  lib/wal/sources/System/ISystem.hpp
  lib/wal/sources/System/System.cpp
  lib/wal/sources/System/System.hpp
  lib/wal/sources/View/View.hpp
  lib/wal/sources/Wal.cpp
  lib/wal/sources/Wal.hpp
  sources/Component/Collision/CollisionComponent.cpp
  sources/Component/Collision/CollisionComponent.hpp
  sources/Component/Movable/MovableComponent.cpp
  sources/Component/Movable/MovableComponent.hpp
  sources/Map/Map.cpp
  sources/Map/Map.hpp
  sources/Models/Vector3.hpp
  sources/Runner/Runner.cpp
  sources/System/Animation/AnimationsSystem.cpp
  sources/System/Animation/AnimationsSystem.hpp
  sources/System/Collision/CollisionSystem.cpp
  sources/System/Collision/CollisionSystem.hpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/Controllable/ControllableSystem.hpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/Gamepad/GamepadSystem.hpp
  sources/System/GridCentered/GridCenteredSystem.cpp
  sources/System/GridCentered/GridCenteredSystem.hpp
  sources/System/Health/HealthSystem.cpp
  sources/System/Health/HealthSystem.hpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/Keyboard/KeyboardSystem.hpp
  sources/System/Movable/MovableSystem.cpp
  sources/System/Movable/MovableSystem.hpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Renderer/RenderSystem.hpp
  tests/CallbackTest.cpp
  tests/CollisionTest.cpp
  tests/EngineTests.cpp
  tests/EntityTests.cpp
  tests/MoveTests.cpp
  tests/ViewTest.cpp
Labels: ECS, enhancement

#115 Add Cache system for audio-related material
  lib/Ray/sources/Audio/Music.cpp
  lib/Ray/sources/Audio/Music.hpp
  lib/Ray/sources/Audio/Sound.cpp
  lib/Ray/sources/Audio/Sound.hpp
  lib/Ray/sources/Utils/Cache.hpp
Labels: Encapsulation

#117 Animator
  CMakeLists.txt
  sources/Component/Animator/AnimatorComponent.cpp
  sources/Component/Animator/AnimatorComponent.hpp
  sources/Component/Health/HealthComponent.cpp
  sources/Component/Health/HealthComponent.hpp
  sources/Models/Vector2.hpp
  sources/Runner/Runner.cpp
  sources/System/Animator/AnimatorSystem.cpp
  sources/System/Animator/AnimatorSystem.hpp
  sources/System/Health/HealthSystem.cpp
Labels: Game

#121 Bombs
  CMakeLists.txt
  lib/wal/sources/Entity/Entity.cpp
  lib/wal/sources/Entity/Entity.hpp
  lib/wal/sources/Scene/Scene.cpp
  lib/wal/sources/Scene/Scene.hpp
  lib/wal/sources/View/View.hpp
  lib/wal/sources/Wal.hpp
  sources/Component/BombHolder/BombHolderComponent.cpp
  sources/Component/BombHolder/BombHolderComponent.hpp
  sources/Component/Health/HealthComponent.cpp
  sources/Component/Health/HealthComponent.hpp
  sources/Component/Timer/TimerComponent.cpp
  sources/Component/Timer/TimerComponent.hpp
  sources/Map/Map.cpp
  sources/Map/Map.hpp
  sources/Runner/Runner.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
  sources/System/BombHolder/BombHolderSystem.hpp
  sources/System/Event/EventSystem.cpp
  sources/System/Event/EventSystem.hpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/Keyboard/KeyboardSystem.hpp
  sources/System/Timer/TimerSystem.cpp
  sources/System/Timer/TimerSystem.hpp
  tests/ViewTest.cpp
Labels: Game, component

#123 Collisions fix
  CMakeLists.txt
  sources/Component/Collision/CollisionComponent.cpp
  sources/Component/Collision/CollisionComponent.hpp
  sources/Map/Map.cpp
  sources/Map/Map.hpp
  sources/Runner/Runner.cpp
  sources/System/Collision/CollisionSystem.cpp
  sources/System/Collision/CollisionSystem.hpp
  sources/System/Renderer/RenderSystem.cpp
  tests/CollisionTest.cpp
Labels: bug

#126 Gamepad component now supports joystick input
  lib/Ray/sources/Controllers/Gamepad.cpp
  lib/Ray/sources/Controllers/Gamepad.hpp
  sources/Component/Gamepad/GamepadComponent.hpp
  sources/Component/Keyboard/KeyboardComponent.hpp
  sources/Runner/Runner.cpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/Keyboard/KeyboardSystem.cpp
Labels: Encapsulation, bug

#127 Music/Sound component
  CMakeLists.txt
  assets/musics/music_win.ogg
  assets/sounds/bomb_drop.ogg
  assets/sounds/death.ogg
  assets/sounds/fuse.ogg
  assets/sounds/jump.wav
  assets/sounds/move.ogg
  lib/Ray/sources/Audio/Music.cpp
  lib/Ray/sources/Audio/Music.hpp
  lib/Ray/sources/Window.cpp
  sources/Component/Music/MusicComponent.cpp
  sources/Component/Music/MusicComponent.hpp
  sources/Component/Sound/SoundComponent.cpp
  sources/Component/Sound/SoundComponent.hpp
  sources/Runner/Runner.cpp
  sources/System/Music/MusicSystem.cpp
  sources/System/Music/MusicSystem.hpp
  sources/System/Sound/PlayerSoundManagerSystem.cpp
  sources/System/Sound/PlayerSoundManagerSystem.hpp
Labels: Game, component

#130 replace stairs by bumper and add assets for it
  assets/map/bumper.png
  sources/Map/Map.cpp
  sources/Map/Map.hpp
Labels: Game, bug

#133 Bomb wall
  CMakeLists.txt
  sources/Component/Tag/TagComponent.hpp
  sources/Map/Map.cpp
  sources/Models/Vector3.hpp
  sources/Runner/Runner.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
  sources/System/BombHolder/BombHolderSystem.hpp
  sources/System/Event/EventSystem.cpp
  sources/System/Event/EventSystem.hpp
  tests/CollisionTest.cpp
Labels: Game

#135 add cache to sound
  sources/Component/Sound/SoundComponent.cpp
  sources/Component/Sound/SoundComponent.hpp
  sources/Runner/Runner.cpp
Labels: Game, bug

#129 First Menus
  CMakeLists.txt
  assets/bomberman.TTF
  assets/buttons/button_back.png
  assets/buttons/button_back_hovered.png
  assets/buttons/button_exit.png
  assets/buttons/button_exit_hovered.png
  assets/buttons/button_minus.png
  assets/buttons/button_minus_hovered.png
  assets/buttons/button_new_game.png
  assets/buttons/button_new_game_hovered.png
  assets/buttons/button_plus.png
  assets/buttons/button_plus_hovered.png
  assets/buttons/button_settings.png
  assets/buttons/button_settings_hovered.png
  assets/buttons/tickbox_ticked.png
  assets/buttons/tickbox_unticked.png
  assets/logo_big.png
  assets/logo_small.png
  assets/musics/music_battle.ogg
  assets/musics/music_player_select.ogg
  assets/musics/music_result.ogg
  assets/musics/music_title.ogg
  assets/plain_menu_background.png
  assets/raylib.png
  assets/sounds/click.ogg
  lib/Ray/sources/Drawables/Image.cpp
  lib/Ray/sources/Drawables/Image.hpp
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  lib/Ray/sources/Window.cpp
  lib/Ray/sources/Window.hpp
  lib/wal/sources/Entity/Entity.cpp
  lib/wal/sources/Entity/Entity.hpp
  lib/wal/sources/Scene/Scene.cpp
  sources/Component/Button/ButtonComponent.hpp
  sources/Component/Keyboard/KeyboardComponent.hpp
  sources/Component/Music/MusicComponent.cpp
  sources/Component/Music/MusicComponent.hpp
  sources/Component/Sound/SoundComponent.cpp
  sources/Component/Sound/SoundComponent.hpp
  sources/Models/GameState.hpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.hpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Renderer/RenderSystem.hpp
  sources/System/Sound/MenuSoundManagerSystem.cpp
  sources/System/Sound/MenuSoundManagerSystem.hpp
  sources/main.cpp
Labels: Game

#138 player models are now independant
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  sources/Component/Keyboard/KeyboardComponent.cpp
  sources/Component/Keyboard/KeyboardComponent.hpp
  sources/Map/Map.cpp
  sources/Runner/Runner.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
Labels: bug

#153 Intro Animation / Splash Screen
  CMakeLists.txt
  assets/sounds/splash_sound.ogg
  lib/Ray/sources/Drawables/2D/Rectangle.cpp
  lib/Ray/sources/Drawables/2D/Rectangle.hpp
  sources/Component/IntroAnimation/IntroAnimationComponent.cpp
  sources/Component/IntroAnimation/IntroAnimationComponent.hpp
  sources/Models/GameState.hpp
  sources/Runner/CreditScene.cpp
  sources/Runner/GameScene.cpp
  sources/Runner/MainMenuScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/Runner/SettingsMenuScene.cpp
  sources/Runner/SplashScreenScene.cpp
  sources/Runner/TitleScreenScene.cpp
  sources/System/IntroAnimation/IntroAnimationSystem.cpp
  sources/System/IntroAnimation/IntroAnimationSystem.hpp
Labels: Game

#154 Draw Wires and bounding boxes in debug mode
  lib/Ray/sources/Drawables/3D/Cube.cpp
  lib/Ray/sources/Drawables/3D/Cube.hpp
  lib/Ray/sources/Drawables/3D/Cylinder.cpp
  lib/Ray/sources/Drawables/3D/Cylinder.hpp
  lib/Ray/sources/Drawables/3D/Sphere.cpp
  lib/Ray/sources/Drawables/3D/Sphere.hpp
  lib/Ray/sources/Drawables/ADrawable3D.cpp
  lib/Ray/sources/Drawables/ADrawable3D.hpp
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  sources/Map/Map.cpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Renderer/RenderSystem.hpp
Labels: Encapsulation, Game, renderer

#155 Making bonuses blowable and fix bomb
  sources/Map/Map.cpp
  sources/Models/Vector3.hpp
  sources/System/BombHolder/BombHolderSystem.cpp
  sources/System/BombHolder/BombHolderSystem.hpp
  sources/System/Collision/CollisionSystem.cpp
  sources/System/Collision/CollisionSystem.hpp
  tests/CollisionTest.cpp
Labels: Game, bug

#157 Gravity component
  CMakeLists.txt
  sources/Component/BumperTimer/BumperTimerComponent.cpp
  sources/Component/BumperTimer/BumperTimerComponent.hpp
  sources/Component/Gravity/GravityComponent.cpp
  sources/Component/Gravity/GravityComponent.hpp
  sources/Map/Map.cpp
  sources/Map/Map.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/Runner.cpp
  sources/System/BombHolder/BombHolderSystem.hpp
  sources/System/BumperTimer/BumperTimerSystem.cpp
  sources/System/BumperTimer/BumperTimerSystem.hpp
  sources/System/Gravity/GravitySystem.cpp
  sources/System/Gravity/GravitySystem.hpp
Labels: Game, bug

#168 Micro PR : Collision fix
  sources/Map/Map.cpp
Labels: Game, bug

#158 Adding a lobby
  CMakeLists.txt
  assets/player/icons/ai.png
  assets/player/icons/blue.png
  assets/player/icons/green.png
  assets/player/icons/none.png
  assets/player/icons/ready.png
  assets/player/icons/red.png
  assets/player/icons/yellow.png
  assets/player/textures/blue.png
  assets/player/textures/cyan.png
  assets/player/textures/green.png
  assets/player/textures/purple.png
  assets/player/textures/red.png
  assets/player/textures/yellow.png
  lib/Ray/sources/Drawables/2D/Rectangle.hpp
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  lib/Ray/sources/Model/ModelAnimation.cpp
  lib/Ray/sources/Model/ModelAnimation.hpp
  lib/Ray/sources/Model/ModelAnimations.hpp
  lib/Ray/sources/Utils/Cache.hpp
  lib/wal/sources/Scene/Scene.hpp
  lib/wal/sources/View/View.hpp
  sources/Component/Animation/AnimationsComponent.cpp
  sources/Component/Animation/AnimationsComponent.hpp
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Component/Gamepad/GamepadComponent.cpp
  sources/Component/Gamepad/GamepadComponent.hpp
  sources/Component/Keyboard/KeyboardComponent.cpp
  sources/Component/Keyboard/KeyboardComponent.hpp
  sources/Component/Lobby/LobbyComponent.cpp
  sources/Component/Lobby/LobbyComponent.hpp
  sources/Runner/CreditScene.cpp
  sources/Runner/GameScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/MainMenuScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/Runner/SettingsMenuScene.cpp
  sources/Runner/SplashScreenScene.cpp
  sources/Runner/TitleScreenScene.cpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Lobby/LobbySystem.hpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.hpp
Labels: Game, enhancement, help wanted

#166 Micro PR: Bomb explosion chain
  sources/Component/Tag/TagComponent.hpp
  sources/Map/Map.cpp
  sources/Runner/GameScene.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
Labels: Game, enhancement

#170 Manage End Condition + Score Scene
  CMakeLists.txt
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  sources/Component/Score/ScoreComponent.cpp
  sources/Component/Score/ScoreComponent.hpp
  sources/Models/GameState.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/Runner/ScoreScene.cpp
  sources/System/EndCondition/EndConditionSystem.cpp
  sources/System/EndCondition/EndConditionSystem.hpp
  sources/System/Score/ScoreSystem.cpp
  sources/System/Score/ScoreSystem.hpp
Labels: Game

#172 Bots & heights in the lobby.
  assets/buttons/cpu_add.png
  assets/buttons/cpu_add_hovered.png
  assets/buttons/cpu_remove.png
  assets/buttons/cpu_remove_hovered.png
  assets/player/icons/ai.png
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Lobby/LobbySystem.hpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/Sound/MenuSoundManagerSystem.cpp
  sources/System/Sound/PlayerSoundManagerSystem.cpp
Labels: Game

#176 Adding a map BG and explosions looks nicer
  CMakeLists.txt
  assets/background_game.png
  assets/shaders/alpha.fs
  assets/shaders/bomb.vs
  assets/shaders/explosion.fs
  assets/shaders/explosion.vs
  assets/shaders/white.fs
  lib/Ray/CMakeLists.txt
  lib/Ray/sources/Drawables/2D/Rectangle.cpp
  lib/Ray/sources/Drawables/2D/Rectangle.hpp
  lib/Ray/sources/Drawables/ADrawable2D.cpp
  lib/Ray/sources/Drawables/ADrawable2D.hpp
  lib/Ray/sources/Drawables/Image.hpp
  lib/Ray/sources/Drawables/Texture.cpp
  lib/Ray/sources/Drawables/Texture.hpp
  lib/Ray/sources/Meshes/AMesh.cpp
  lib/Ray/sources/Meshes/AMesh.hpp
  lib/Ray/sources/Meshes/MeshSphere.cpp
  lib/Ray/sources/Meshes/MeshSphere.hpp
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  lib/Ray/sources/Shaders/Shaders.cpp
  lib/Ray/sources/Shaders/Shaders.hpp
  lib/Ray/sources/Utils/Cache.hpp
  sources/Component/Renderer/Drawable2DComponent.hpp
  sources/Component/Shaders/Items/BombExplosionShaderComponent.cpp
  sources/Component/Shaders/Items/BombExplosionShaderComponent.hpp
  sources/Component/Shaders/Items/WhiteShaderComponent.cpp
  sources/Component/Shaders/Items/WhiteShaderComponent.hpp
  sources/Component/Shaders/ShaderComponent.cpp
  sources/Component/Shaders/ShaderComponent.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/Runner.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Shaders/ShaderDrawable2DSystem.cpp
  sources/System/Shaders/ShaderDrawable2DSystem.hpp
  sources/System/Shaders/ShaderModelSystem.cpp
  sources/System/Shaders/ShaderModelSystem.hpp
  sources/System/Shaders/ShaderSystem.cpp
  sources/System/Shaders/ShaderSystem.hpp
Labels: Game

#180 Managable Window Size
  lib/Ray/sources/Window.cpp
  lib/Ray/sources/Window.hpp
  screenshot000.png
  sources/Runner/Runner.cpp
  sources/Runner/SettingsMenuScene.cpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.hpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Renderer/RenderSystem.hpp
Labels: UI/UX

#183 Fix Sound On Click
  sources/Runner/CreditScene.cpp
  sources/Runner/HowToPlayScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/MainMenuScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/Runner/ScoreScene.cpp
  sources/Runner/SettingsMenuScene.cpp
  sources/Runner/TitleScreenScene.cpp
Labels: UI/UX, bug

#187 Player pos fix with height
  sources/Runner/GameScene.cpp
  sources/System/Lobby/LobbySystem.cpp
Labels: Game, bug

#189 Bombs fix
  sources/Component/Bomb/BasicBombComponent.cpp
  sources/Component/Bomb/BasicBombComponent.hpp
  sources/System/Bomb/BombSystem.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
  sources/System/BombHolder/BombHolderSystem.hpp
Labels: Game, bug

#188 UI Improvement (Vol. 2)
  lib/Ray/sources/Window.cpp
  lib/Ray/sources/Window.hpp
  sources/Runner/Runner.cpp
  sources/Runner/SettingsMenuScene.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/Renderer/RenderSystem.cpp
Labels: UI/UX

#185 Fix player death
  lib/wal/sources/Entity/Entity.hpp
  lib/wal/sources/System/System.hpp
  sources/Runner/GameScene.cpp
  sources/System/Animator/AnimatorSystem.cpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/EndCondition/EndConditionSystem.cpp
  sources/System/EndCondition/EndConditionSystem.hpp
  sources/System/Event/EventSystem.cpp
  sources/System/Event/EventSystem.hpp
  sources/System/IAControllable/IAControllableSystem.cpp
  sources/System/IAControllable/IAControllableSystem.hpp
  sources/System/IntroAnimation/IntroAnimationSystem.cpp
  sources/System/IntroAnimation/IntroAnimationSystem.hpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Lobby/LobbySystem.hpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.hpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Renderer/RenderSystem.hpp
Labels: Game, bug

#191 Update texture
  assets/background.png
  assets/background_game.png
  assets/map/floor.png
  assets/map/hole.png
  lib/Ray/sources/Model/Model.cpp
  lib/Ray/sources/Model/Model.hpp
  sources/Items/Bonus.cpp
  sources/Map/Map.cpp
  sources/Runner/GameScene.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Renderer/RenderSystem.cpp
Labels: Game

#175 Camera system
  CMakeLists.txt
  sources/Component/Tag/TagComponent.hpp
  sources/Models/Vector3.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/Runner.cpp
  sources/System/Animator/AnimatorSystem.cpp
  sources/System/Renderer/CameraSystem.cpp
  sources/System/Renderer/CameraSystem.hpp
  sources/System/Renderer/RenderSystem.cpp
  sources/System/Renderer/RenderSystem.hpp
Labels: Game

#212 Fix bonus and map
  assets/map/bumper.png
  assets/map/outer_wall.mtl
  assets/map/outer_wall.obj
  assets/map/outer_wall.png
  sources/Items/Bonus.cpp
  sources/Map/Map.cpp
  sources/Map/Map.hpp
Labels: Game, bug

#215 UI Improvement (Level 3)
  README.md
  assets/backgrounds/credit.png
  assets/backgrounds/game.png
  assets/backgrounds/menu.png
  assets/backgrounds/pause.png
  assets/backgrounds/plain.png
  assets/backgrounds/score.png
  assets/backgrounds/settings.png
  assets/credit/art.png
  assets/credit/blu.png
  assets/credit/ete.png
  assets/credit/oct.png
  assets/credit/rac.png
  assets/credit/tru.png
  assets/epitech.png
  assets/game_background.png
  lib/wal/sources/Component/Component.cpp
  lib/wal/sources/Component/Component.hpp
  lib/wal/sources/Entity/Entity.cpp
  lib/wal/sources/Entity/Entity.hpp
  sources/Component/Animation/AnimationsComponent.cpp
  sources/Component/Controllable/ControllableComponent.cpp
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Component/IntroAnimation/IntroAnimationComponent.hpp
  sources/Runner/CreditScene.cpp
  sources/Runner/GameScene.cpp
  sources/Runner/HowToPlayScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/MainMenuScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/ScoreScene.cpp
  sources/Runner/SettingsMenuScene.cpp
  sources/Runner/SplashScreenScene.cpp
  sources/Runner/TitleScreenScene.cpp
  sources/System/Animation/AnimationsSystem.cpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/IAControllable/IAControllableSystem.cpp
  sources/System/IntroAnimation/IntroAnimationSystem.cpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Lobby/LobbySystem.hpp
  sources/System/Renderer/CameraSystem.cpp
  sources/System/Renderer/CameraSystem.hpp
  sources/System/Timer/TimerSystem.cpp
  sources/System/Timer/TimerUISystem.cpp
Labels: Game, UI/UX

#227 Add Controls to Lobby Scene
  sources/Runner/LobbyScene.cpp
Labels: UI/UX

#229 Shader no clip
  CMakeLists.txt
  assets/shaders/explosion.vs
  lib/Ray/sources/Shaders/Shaders.cpp
  lib/Ray/sources/Shaders/Shaders.hpp
  sources/Component/Shaders/Items/AlphaCtxShaderComponent.cpp
  sources/Component/Shaders/Items/AlphaCtxShaderComponent.hpp
  sources/Items/Bonus.cpp
  sources/Runner/GameScene.cpp
  sources/System/BombHolder/BombHolderSystem.cpp
Labels: Game

#223 Menus improvements
  .gitignore
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Component/Gamepad/GamepadComponent.hpp
  sources/Component/Keyboard/KeyboardComponent.cpp
  sources/Component/Keyboard/KeyboardComponent.hpp
  sources/Component/Timer/TimerComponent.hpp
  sources/Models/GameState.hpp
  sources/Runner/HowToPlayScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/ScoreScene.cpp
  sources/Runner/SettingsMenuScene.cpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/EndCondition/EndConditionSystem.cpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/IAControllable/IAControllableSystem.cpp
  sources/System/Keyboard/KeyboardSystem.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/Renderer/CameraSystem.cpp
  sources/System/Sound/MenuSoundManagerSystem.cpp
  sources/System/Sound/PlayerSoundManagerSystem.cpp
  sources/System/Timer/TimerSystem.cpp
Labels: Game

#220 Background parallax
  assets/backgrounds/gameWall.png
  lib/Ray/sources/Drawables/3D/Plane.cpp
  sources/Component/Tag/TagComponent.hpp
  sources/Models/Vector2.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/Runner.cpp
  sources/System/Renderer/CameraSystem.cpp
Labels: UI/UX, renderer

#224 No clip fixes
  sources/Items/Bonus.cpp
  sources/Map/Map.cpp
  sources/Runner/GameScene.cpp
  sources/System/Bonus/PlayerBonusSystem.cpp
  sources/System/Renderer/CameraSystem.cpp
Labels: Game, bug

#238 Raylib
  lib/raylib/Findraylib.cmake
Labels: renderer

#241 Fixes
  sources/Runner/GameScene.cpp
  sources/System/Gamepad/GamepadSystem.cpp
  sources/System/Gamepad/GamepadSystem.hpp
  sources/System/Renderer/CameraSystem.cpp
Labels: Game

#230 Parser
  .gitignore
  CMakeLists.txt
  assets/buttons/button_resume_game.png
  assets/buttons/button_resume_game_hovered.png
  assets/buttons/button_save.png
  assets/buttons/button_save_hovered.png
  lib/Ray/sources/Vector/Vector3.cpp
  lib/wal/sources/Entity/Entity.cpp
  lib/wal/sources/Entity/Entity.hpp
  sources/Component/BombHolder/BombHolderComponent.cpp
  sources/Component/BombHolder/BombHolderComponent.hpp
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Component/Lobby/ResumeLobbyComponent.cpp
  sources/Component/Lobby/ResumeLobbyComponent.hpp
  sources/Component/Speed/SpeedComponent.cpp
  sources/Component/Speed/SpeedComponent.hpp
  sources/Component/Tag/TagComponent.hpp
  sources/Exception/Error.cpp
  sources/Exception/Error.hpp
  sources/Items/Bonus.cpp
  sources/Items/Bonus.hpp
  sources/Map/Map.cpp
  sources/Map/Map.hpp
  sources/Models/GameState.hpp
  sources/Parser/Node.cpp
  sources/Parser/Node.hpp
  sources/Parser/ParserYaml.cpp
  sources/Parser/ParserYaml.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/MainMenuScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/ResumeLobbyScene.cpp
  sources/Runner/Runner.cpp
  sources/Runner/Runner.hpp
  sources/System/Controllable/ControllableSystem.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Lobby/LobbySystem.hpp
  sources/System/Lobby/ResumeLobbySystem.cpp
  sources/System/Lobby/ResumeLobbySystem.hpp
  sources/System/Renderer/CameraSystem.cpp
  sources/System/Timer/TimerUISystem.cpp
  sources/System/Timer/TimerUISystem.hpp
  sources/Utils/Utils.cpp
  sources/Utils/Utils.hpp
  tests/MoveTests.cpp
  tests/ViewTest.cpp
Labels: Game, REQUIRED

#243 Player Tiles In-Game are Transparant
  .gitignore
  sources/System/Lobby/LobbySystem.cpp
Labels: UI/UX

#244 Add Screenshot & Demo Link to Readme
  README.md
  assets/images/game.png
  assets/images/lobby.png
  assets/images/titlescreen.png
  images/game.png
  images/lobby.png
  images/titlescreen.png
Labels: UI/UX

#234 Ai script
  CMakeLists.txt
  assets/ai_scripts/jean.lua
  assets/ai_scripts/john.lua
  lib/LuaGate/sources/LuaGate.cpp
  lib/LuaGate/sources/LuaGate.hpp
  sources/Component/IAControllable/IAControllableComponent.cpp
  sources/Component/IAControllable/IAControllableComponent.hpp
  sources/Map/LuaMap.cpp
  sources/Map/LuaMap.hpp
  sources/Runner/GameScene.cpp
  sources/System/IAControllable/IAControllableSystem.cpp
  sources/System/IAControllable/IAControllableSystem.hpp
Labels: Game

#246 it's better (animations optis)
  sources/Component/Animation/AnimationsComponent.hpp
  sources/System/Animation/AnimationsSystem.cpp
  sources/System/Animation/AnimationsSystem.hpp
Labels: Game, enhancement

#250 fix berserk camera
  sources/Runner/GameScene.cpp
  sources/System/Renderer/CameraSystem.cpp
Labels: Game, bug, renderer

#254 lua misc fixes
  sources/Component/IAControllable/IAControllableComponent.cpp
Labels: bug

#256 Fix
  sources/Component/Tag/TagComponent.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/ResumeLobbyScene.cpp
  sources/Runner/ScoreScene.cpp
  sources/System/Lobby/LobbySystem.cpp
  sources/System/Lobby/LobbySystem.hpp
  sources/System/Lobby/ResumeLobbySystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.cpp
  sources/System/MenuControllable/MenuControllableSystem.hpp
Labels: Game, bug

#257 Fix Sound Effets
  sources/Runner/CreditScene.cpp
  sources/Runner/GameScene.cpp
  sources/Runner/HowToPlayScene.cpp
  sources/Runner/LobbyScene.cpp
  sources/Runner/MainMenuScene.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/Runner/ResumeLobbyScene.cpp
  sources/Runner/ScoreScene.cpp
  sources/Runner/SettingsMenuScene.cpp
  sources/Runner/TitleScreenScene.cpp
Labels: UI/UX, bug

#258 Fixing timer save
  sources/Parser/ParserYaml.cpp
  sources/Utils/Utils.cpp
  sources/Utils/Utils.hpp
Labels: bug

#259 Fix parser
  sources/Parser/ParserYaml.cpp
  sources/Runner/PauseMenuScene.cpp
  sources/System/Lobby/ResumeLobbySystem.cpp
Labels: bug

#260 Fixing the pause movements
  sources/Component/Controllable/ControllableComponent.cpp
  sources/Component/Controllable/ControllableComponent.hpp
  sources/Runner/GameScene.cpp
  sources/Runner/PauseMenuScene.cpp
Labels: bug

#262 Ai inprovements
  Bot.md
  assets/ai_scripts/john.lua
  lib/LuaGate/sources/LuaGate.cpp
  lib/LuaGate/sources/LuaGate.hpp
  sources/Component/IAControllable/IAControllableComponent.cpp
  sources/Map/LuaMap.cpp
  sources/Map/LuaMap.hpp
  sources/System/IAControllable/IAControllableSystem.cpp
Labels: documentation

#266 Upgrade John
  assets/ai_scripts/john.lua
Labels: Game
